project:
  type: website

website:
  site-url: https://bickel.stat.berkeley.edu
  navbar:
    right:
      - href: index.qmd
      - href: research.qmd
      - href: teaching.qmd
      - href: students.qmd
      - href: personal.qmd
    title: "Peter J. Bickel"
format:
  html:
    theme: cosmo
    toc: true
